=== mattCensus/RESTWGPM/RESTJSONXML/RESTJSONXML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:fgdcreq="../newGPMStd/FGDC_RequiredGPM"
    xmlns:ii="../newGPMStd/GPMIdentificationInfo" 
    xmlns:dq="../newGPMStd/GPMDQ"
    xmlns:spdo="../newGPMStd/Spatial_Data_Organization_Information"
    xmlns:sri="../newGPMStd/Spatial_Reference_Information"
    xmlns:EAI="../newGPMStd/Entity_and_Attribute_Information"
    xmlns:di="../newGPMStd/Distribution_Information"
    xmlns:mri="../newGPMStd/Metadata_Reference_Information"
    xmlns:GPMDef="../newGPMStd/GPMDefinitions">

    <xsd:annotation>
        <xsd:documentation xml:lang="en">
        </xsd:documentation>
    </xsd:annotation>
    
    <xsd:element name="REST_File">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="currentVersion"/>
                <xsd:element name="serviceDescription"/>
                <xsd:element name="mapName"/>
                <xsd:element name="description"/>
                <xsd:element name="copyrightText"/>
                <xsd:element name="supportsDynamicLayers"/>
                <xsd:element name="URL"/>
                <xsd:element name="layers" type="layersGroup" maxOccurs="unbounded"/>
                <xsd:element name="spatialReference" type="spatialReferenceType"/>
                <xsd:element name="singleFusedMapCache"/>
                <xsd:element name="initialExtent" type="initialExtentType"/>
                <xsd:element name="fullExtent" type="initialExtentType"/>
                <xsd:element name="minScale"/>
                <xsd:element name="maxScale"/>
                <xsd:element name="units"/>
                <xsd:element name="supportedImageFormatTypes"/>
                <xsd:element name="documentInfo" type="documentInfoType"/>
                <xsd:element name="capabilities"/>
                <xsd:element name="supportedQueryFormats"/>
                <xsd:element name="exportTilesAllowed"/>
                <xsd:element name="datumTransformations" type="datumTransformationsType" maxOccurs="unbounded"/>
                <xsd:element name="supportsDatumTransformation"/>
                <xsd:element name="maxRecordCount"/>
                <xsd:element name="maxImageHeight"/>
                <xsd:element name="maxImageWidth"/>
                <xsd:element name="supportedExtensions"/>
            </xsd:sequence>
        </xsd:complexType>
        
    </xsd:element>

    <xsd:complexType name="datumTransformationsType">
      <xsd:sequence>
          <xsd:element name="geoTransforms" type="geoTransformsType"/>
      </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="geoTransformsType">
        <xsd:sequence> 
            <xsd:element name="wkt" minOccurs="0"/>
            <xsd:element name="wkid" minOccurs="0"/>
            <xsd:element name="latestWkid" minOccurs="0"/>
            <xsd:element name="transformForward"/>
            <xsd:element name="name"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="layersGroup">
        <xsd:sequence>
            <xsd:element name="id"/>
            <xsd:element name="name"/>
            <xsd:element name="parentLayerId"/>
            <xsd:element name="defaultVisibility"/>
            <xsd:element name="subLayerIds" maxOccurs="unbounded"/>
            <xsd:element name="minScale" minOccurs="0"/>
            <xsd:element name="maxScale" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="spatialReferenceType">
        <xsd:sequence>
            <xsd:element name="wkt" minOccurs="0"/>
            <xsd:element name="wkid" minOccurs="0"/>
            <xsd:element name="latestWkid"></xsd:element>
          </xsd:sequence>  
    </xsd:complexType>
    
    <xsd:complexType name="initialExtentType">
        <xsd:sequence>
            <xsd:element name="xmin"/>
            <xsd:element name="ymin"/>
            <xsd:element name="xmax"/>
            <xsd:element name="ymax"/>
            <xsd:element name="spatialReference" type="spatialReferenceType"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="documentInfoType">
        <xsd:sequence>
            <xsd:element name="Title"/>
            <xsd:element name="Author"/>
            <xsd:element name="Comments"/>
            <xsd:element name="Subject"/>
            <xsd:element name="Category"/>
            <xsd:element name="AntialiasingMode"/>
            <xsd:element name="TextAntialiasingMode"/>
            <xsd:element name="Keywords"/>
        </xsd:sequence>
    </xsd:complexType>
  
</xs:schema>

=== mattCensus/RESTWGPM/RESTJSONXML/TIGERweb_Special_Land_Use_Areas.xml
<?xml version="1.0" encoding="UTF-8"?>
<REST_File xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="RESTJSONXML.xsd">
<currentVersion>10.51</currentVersion>
<serviceDescription>Military reservations</serviceDescription>
<mapName>Military and Other Special Land Use Areas</mapName>
<description>Military Installations; National Park Service Areas; Correctional Facilities; Colleges and Universities</description>
<copyrightText>Source: U.S. Census Bureau</copyrightText>
<supportsDynamicLayers>false</supportsDynamicLayers>
	<URL>https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Special_Land_Use_Areas/MapServer</URL>
<layers>
	<id>0</id>
	<name>National Park Service Areas</name>
	<parentLayerId>-1</parentLayerId>
	<defaultVisibility>true</defaultVisibility>
	<subLayerIds>null</subLayerIds>
	<minScale>6000000</minScale>
	<maxScale>1001</maxScale>
</layers>
<layers>
	<id>1</id>
	<name>Correctional Facilities</name>
	<parentLayerId>-1</parentLayerId>
	<defaultVisibility>true</defaultVisibility>
	<subLayerIds>null</subLayerIds>
	<minScale>650000</minScale>
	<maxScale>1001</maxScale>
</layers>
<layers>
	<id>2</id>
	<name>Colleges and Universities</name>
	<parentLayerId>-1</parentLayerId>
	<defaultVisibility>true</defaultVisibility>
	<subLayerIds>null</subLayerIds>
	<minScale>650000</minScale>
	<maxScale>1001</maxScale>
</layers>
<layers>
	<id>3</id>
	<name>Military Installations</name>
	<parentLayerId>-1</parentLayerId>
	<defaultVisibility>true</defaultVisibility>
	<subLayerIds>null</subLayerIds>
	<minScale>2500000</minScale>
	<maxScale>1001</maxScale>
</layers>
<spatialReference>
	<wkid>102100</wkid>
	<latestWkid>3857</latestWkid>
</spatialReference>
<singleFusedMapCache>false</singleFusedMapCache>
<initialExtent>
	<xmin>-8578496.601600984</xmin>
	<ymin>4701429.293652466</ymin>
	<xmax>-8565119.24151293</xmax>
	<ymax>4710933.145993503</ymax>
	<spatialReference>
		<wkid>102100</wkid>
		<latestWkid>3857</latestWkid>
	</spatialReference>
</initialExtent>
<fullExtent>
	<xmin>-1.92056364568E7</xmin>
	<ymin>-1950939.5312</ymin>
	<xmax>1.95172767756E7</xmax>
	<ymax>1.09460453884E7</ymax>
	<spatialReference>
		<wkid>102100</wkid>
		<latestWkid>3857</latestWkid>
	</spatialReference>
</fullExtent>
<minScale>6000000</minScale>
<maxScale>1001</maxScale>
<units>esriMeters</units>
<supportedImageFormatTypes>PNG32,PNG24,PNG,JPG,DIB,TIFF,EMF,PS,PDF,GIF,SVG,SVGZ,BMP</supportedImageFormatTypes>
<documentInfo>
	<Title>Military Reservations</Title>
	<Author/>
	<Comments>Military reservations</Comments>
	<Subject/>
	<Category/>
	<AntialiasingMode>None</AntialiasingMode>
	<TextAntialiasingMode>Force</TextAntialiasingMode>
	<Keywords/>
</documentInfo>
<capabilities>Map,Data,Query</capabilities>
<supportedQueryFormats>JSON, AMF, geoJSON</supportedQueryFormats>
<exportTilesAllowed>false</exportTilesAllowed>
<datumTransformations>
	<geoTransforms>
		<wkid>108001</wkid>
		<latestWkid>1241</latestWkid>
		<transformForward>true</transformForward>
		<name>NAD_1927_To_NAD_1983_NADCON</name>
	</geoTransforms>
</datumTransformations>
<datumTransformations>
	<geoTransforms>
		<wkid>108001</wkid>
		<latestWkid>1241</latestWkid>
		<transformForward>false</transformForward>
		<name>NAD_1927_To_NAD_1983_NADCON</name>
	</geoTransforms>
</datumTransformations>
<datumTransformations>
	<geoTransforms>
		<wkt>GEOGTRAN[&quot;WGS_1984_Major_Auxiliary_Sphere_To_WGS_1984&quot;,GEOGCS[&quot;GCS_WGS_1984_Major_Auxiliary_Sphere&quot;,DATUM[&quot;D_WGS_1984_Major_Auxiliary_Sphere&quot;,SPHEROID[&quot;WGS_1984_Major_Auxiliary_Sphere&quot;,6378137.0,0.0]],PRIMEM[&quot;Greenwich&quot;,0.0],UNIT[&quot;Degree&quot;,0.0174532925199433]],GEOGCS[&quot;GCS_WGS_1984&quot;,DATUM[&quot;D_WGS_1984&quot;,SPHEROID[&quot;WGS_1984&quot;,6378137.0,298.257223563]],PRIMEM[&quot;Greenwich&quot;,0.0],UNIT[&quot;Degree&quot;,0.0174532925199433]],METHOD[&quot;Longitude_Rotation&quot;]]</wkt>
		<transformForward>true</transformForward>
		<name>WGS_1984_Major_Auxiliary_Sphere_To_WGS_1984</name>
	</geoTransforms>
</datumTransformations>
<datumTransformations>
	<geoTransforms>
		<wkt>GEOGTRAN[&quot;WGS_1984_Major_Auxiliary_Sphere_To_WGS_1984&quot;,GEOGCS[&quot;GCS_WGS_1984_Major_Auxiliary_Sphere&quot;,DATUM[&quot;D_WGS_1984_Major_Auxiliary_Sphere&quot;,SPHEROID[&quot;WGS_1984_Major_Auxiliary_Sphere&quot;,6378137.0,0.0]],PRIMEM[&quot;Greenwich&quot;,0.0],UNIT[&quot;Degree&quot;,0.0174532925199433]],GEOGCS[&quot;GCS_WGS_1984&quot;,DATUM[&quot;D_WGS_1984&quot;,SPHEROID[&quot;WGS_1984&quot;,6378137.0,298.257223563]],PRIMEM[&quot;Greenwich&quot;,0.0],UNIT[&quot;Degree&quot;,0.0174532925199433]],METHOD[&quot;Longitude_Rotation&quot;]]</wkt>
		<transformForward>false</transformForward>
		<name>WGS_1984_Major_Auxiliary_Sphere_To_WGS_1984</name>
	</geoTransforms>
</datumTransformations>
<datumTransformations>
	<geoTransforms>
		<wkid>8088</wkid>
		<latestWkid>1188</latestWkid>
		<transformForward>true</transformForward>
		<name>NAD_1983_To_WGS_1984_1</name>
	</geoTransforms>
</datumTransformations>
<datumTransformations>
	<geoTransforms>
		<wkid>8088</wkid>
		<latestWkid>1188</latestWkid>
		<transformForward>false</transformForward>
		<name>NAD_1983_To_WGS_1984_1</name>
	</geoTransforms>
</datumTransformations>
<supportsDatumTransformation>true</supportsDatumTransformation>
<maxRecordCount>100000</maxRecordCount>
<maxImageHeight>4096</maxImageHeight>
<maxImageWidth>4096</maxImageWidth>
<supportedExtensions/>
</REST_File>
