=== mattCensus/RESTWGPM/RESTJSONXML/RESTJSONXML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:fgdcreq="../newGPMStd/FGDC_RequiredGPM"
    xmlns:ii="../newGPMStd/GPMIdentificationInfo" 
    xmlns:dq="../newGPMStd/GPMDQ"
    xmlns:spdo="../newGPMStd/Spatial_Data_Organization_Information"
    xmlns:sri="../newGPMStd/Spatial_Reference_Information"
    xmlns:EAI="../newGPMStd/Entity_and_Attribute_Information"
    xmlns:di="../newGPMStd/Distribution_Information"
    xmlns:mri="../newGPMStd/Metadata_Reference_Information"
    xmlns:GPMDef="../newGPMStd/GPMDefinitions">

    <xsd:annotation>
        <xsd:documentation xml:lang="en">
        </xsd:documentation>
    </xsd:annotation>
    
    <xsd:element name="REST_File">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="currentVersion"/>
                <xsd:element name="serviceDescription"/>
                <xsd:element name="mapName"/>
                <xsd:element name="description"/>
                <xsd:element name="copyrightText"/>
                <xsd:element name="supportsDynamicLayers"/>
                <xsd:element name="URL"/>
                <xsd:element name="layers" type="layersGroup" maxOccurs="unbounded"/>
                <xsd:element name="spatialReference" type="spatialReferenceType"/>
                <xsd:element name="singleFusedMapCache"/>
                <xsd:element name="initialExtent" type="initialExtentType"/>
                <xsd:element name="fullExtent" type="initialExtentType"/>
                <xsd:element name="minScale"/>
                <xsd:element name="maxScale"/>
                <xsd:element name="units"/>
                <xsd:element name="supportedImageFormatTypes"/>
                <xsd:element name="documentInfo" type="documentInfoType"/>
                <xsd:element name="capabilities"/>
                <xsd:element name="supportedQueryFormats"/>
                <xsd:element name="exportTilesAllowed"/>
                <xsd:element name="datumTransformations" type="datumTransformationsType" maxOccurs="unbounded"/>
                <xsd:element name="supportsDatumTransformation"/>
                <xsd:element name="maxRecordCount"/>
                <xsd:element name="maxImageHeight"/>
                <xsd:element name="maxImageWidth"/>
                <xsd:element name="supportedExtensions"/>
            </xsd:sequence>
        </xsd:complexType>
        
    </xsd:element>

    <xsd:complexType name="datumTransformationsType">
      <xsd:sequence>
          <xsd:element name="geoTransforms" type="geoTransformsType"/>
      </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="geoTransformsType">
        <xsd:sequence> 
            <xsd:element name="wkt" minOccurs="0"/>
            <xsd:element name="wkid" minOccurs="0"/>
            <xsd:element name="latestWkid" minOccurs="0"/>
            <xsd:element name="transformForward"/>
            <xsd:element name="name"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="layersGroup">
        <xsd:sequence>
            <xsd:element name="id"/>
            <xsd:element name="name"/>
            <xsd:element name="parentLayerId"/>
            <xsd:element name="defaultVisibility"/>
            <xsd:element name="subLayerIds" maxOccurs="unbounded"/>
            <xsd:element name="minScale" minOccurs="0"/>
            <xsd:element name="maxScale" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="spatialReferenceType">
        <xsd:sequence>
            <xsd:element name="wkt" minOccurs="0"/>
            <xsd:element name="wkid" minOccurs="0"/>
            <xsd:element name="latestWkid"></xsd:element>
          </xsd:sequence>  
    </xsd:complexType>
    
    <xsd:complexType name="initialExtentType">
        <xsd:sequence>
            <xsd:element name="xmin"/>
            <xsd:element name="ymin"/>
            <xsd:element name="xmax"/>
            <xsd:element name="ymax"/>
            <xsd:element name="spatialReference" type="spatialReferenceType"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="documentInfoType">
        <xsd:sequence>
            <xsd:element name="Title"/>
            <xsd:element name="Author"/>
            <xsd:element name="Comments"/>
            <xsd:element name="Subject"/>
            <xsd:element name="Category"/>
            <xsd:element name="AntialiasingMode"/>
            <xsd:element name="TextAntialiasingMode"/>
            <xsd:element name="Keywords"/>
        </xsd:sequence>
    </xsd:complexType>
  
</xs:schema>

=== mattCensus/RESTWGPM/RESTJSONXML/TIGERweb_Legislative_Rest.xml
<?xml version="1.0" encoding="UTF-8"?>
<REST_File xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../RESTJSONXML/RESTJSONXML.xsd">
   
<currentVersion>10.51</currentVersion>
<serviceDescription/>
<mapName>Legislative Areas</mapName>
<description>Congressional Districts, Voting Districts, State Legislative Districts - Upper, State Legislative Districts - Lower</description>
<copyrightText>Source: U.S. Census Bureau</copyrightText>
<supportsDynamicLayers>false</supportsDynamicLayers>
    <URL>https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Legislative/MapServer</URL>
<layers>
    <id>0</id>
    <name>116th Congressional Districts</name>
    <parentLayerId>-1</parentLayerId>
    <defaultVisibility>false</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>12000000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>1</id>
    <name>2018 State Legislative Districts - Upper</name>
    <parentLayerId>-1</parentLayerId>
    <defaultVisibility>false</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>2500000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>2</id>
    <name>2018 State Legislative Districts - Lower</name>
    <parentLayerId>-1</parentLayerId>
    <defaultVisibility>false</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>2500000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>3</id>
    <name>ACS 2019</name>
    <parentLayerId>-1</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>4</subLayerIds>
    <subLayerIds>5</subLayerIds>
    <subLayerIds>6</subLayerIds>
    <minScale>0</minScale>
    <maxScale>0</maxScale>
</layers>
<layers>
    <id>4</id>
    <name>116th Congressional Districts</name>
    <parentLayerId>3</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>12000000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>5</id>
    <name>2019 State Legislative Districts - Upper</name>
    <parentLayerId>3</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>2500000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>6</id>
    <name>2019 State Legislative Districts - Lower</name>
    <parentLayerId>3</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>2500000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>7</id>
    <name>ACS 2018</name>
    <parentLayerId>-1</parentLayerId>
    <defaultVisibility>false</defaultVisibility>
    <subLayerIds>8</subLayerIds>
    <subLayerIds>9</subLayerIds>
    <subLayerIds>10</subLayerIds>
    <minScale>0</minScale>
    <maxScale>0</maxScale>
</layers>
<layers>
    <id>8</id>
    <name>116th Congressional Districts</name>
    <parentLayerId>7</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>12000000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>9</id>
    <name>2018 State Legislative Districts - Upper</name>
    <parentLayerId>7</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>2500000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>10</id>
    <name>2018 State Legislative Districts - Lower</name>
    <parentLayerId>7</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>2500000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>11</id>
    <name>Census 2010</name>
    <parentLayerId>-1</parentLayerId>
    <defaultVisibility>false</defaultVisibility>
    <subLayerIds>12</subLayerIds>
    <subLayerIds>13</subLayerIds>
    <subLayerIds>14</subLayerIds>
    <subLayerIds>15</subLayerIds>
    <subLayerIds>16</subLayerIds>
    <subLayerIds>17</subLayerIds>
    <subLayerIds>18</subLayerIds>
    <minScale>0</minScale>
    <maxScale>0</maxScale>
</layers>
<layers>
    <id>12</id>
    <name>113th Congressional Districts</name>
    <parentLayerId>11</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>12000000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>13</id>
    <name>111th Congressional Districts</name>
    <parentLayerId>11</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>12000000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>14</id>
    <name>2013 State Legislative Districts - Upper</name>
    <parentLayerId>11</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>2500000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>15</id>
    <name>2013 State Legislative Districts - Lower</name>
    <parentLayerId>11</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>2500000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>16</id>
    <name>2010 State Legislative Districts - Upper</name>
    <parentLayerId>11</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>2500000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>17</id>
    <name>2010 State Legislative Districts - Lower</name>
    <parentLayerId>11</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>2500000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>18</id>
    <name>Voting Districts</name>
    <parentLayerId>11</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>325000</minScale>
    <maxScale>1001</maxScale>
</layers>
<spatialReference>
    <wkid>102100</wkid>
    <latestWkid>3857</latestWkid>
</spatialReference>
<singleFusedMapCache>false</singleFusedMapCache>
<initialExtent>
    <xmin>-1.0766745686202005E7</xmin>
    <ymin>3777153.0810617693</ymin>
    <xmax>-9548674.959184527</xmax>
    <ymax>4642522.948832098</ymax>
    <spatialReference>
        <wkid>102100</wkid>
        <latestWkid>3857</latestWkid>
    </spatialReference>
</initialExtent>
<fullExtent>
    <xmin>-20037700</xmin>
    <ymin>-1.02529861195E7</ymin>
    <xmax>3.9937569599E7</xmax>
    <ymax>2.9734169599E7</ymax>
    <spatialReference>
        <wkid>102100</wkid>
        <latestWkid>3857</latestWkid>
    </spatialReference>
</fullExtent>
<minScale>12000000</minScale>
<maxScale>1001</maxScale>
<units>esriMeters</units>
<supportedImageFormatTypes>PNG32,PNG24,PNG,JPG,DIB,TIFF,EMF,PS,PDF,GIF,SVG,SVGZ,BMP</supportedImageFormatTypes>
<documentInfo>
    <Title/>
    <Author/>
    <Comments/>
    <Subject/>
    <Category/>
    <AntialiasingMode>None</AntialiasingMode>
    <TextAntialiasingMode>Force</TextAntialiasingMode>
    <Keywords/>
</documentInfo>
<capabilities>Map,Data,Query</capabilities>
<supportedQueryFormats>JSON, AMF, geoJSON</supportedQueryFormats>
<exportTilesAllowed>false</exportTilesAllowed>
<datumTransformations>
    <geoTransforms>
        <wkid>108001</wkid>
        <latestWkid>1241</latestWkid>
        <transformForward>true</transformForward>
        <name>NAD_1927_To_NAD_1983_NADCON</name>
    </geoTransforms>
</datumTransformations>
<datumTransformations>
    <geoTransforms>
        <wkid>108001</wkid>
        <latestWkid>1241</latestWkid>
        <transformForward>false</transformForward>
        <name>NAD_1927_To_NAD_1983_NADCON</name>
    </geoTransforms>
</datumTransformations>
<supportsDatumTransformation>true</supportsDatumTransformation>
<maxRecordCount>100000</maxRecordCount>
<maxImageHeight>4096</maxImageHeight>
<maxImageWidth>4096</maxImageWidth>
<supportedExtensions/>
</REST_File>

=== mattCensus/RESTWGPM/RESTJSONXML/TIGERweb_PUMA_TAD_TAZ_UGA_ZCTA.xml
<?xml version="1.0" encoding="UTF-8"?>
<REST_File xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="RESTJSONXML.xsd">
<currentVersion>10.51</currentVersion>
<serviceDescription/>
<mapName>PUMAs, UGAs, and ZCTAs</mapName>
<description>Urban Growth Areas, ZIP Code Tabulation Areas</description>
<copyrightText>Source: U.S. Census Bureau</copyrightText>
<supportsDynamicLayers>false</supportsDynamicLayers>
	<URL>https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/PUMA_TAD_TAZ_UGA_ZCTA/MapServer</URL>
<layers>
	<id>0</id>
	<name>2010 Census Public Use Microdata Areas</name>
	<parentLayerId>-1</parentLayerId>
	<defaultVisibility>true</defaultVisibility>
	<subLayerIds>null</subLayerIds>
	<minScale>12000000</minScale>
	<maxScale>1001</maxScale>
</layers>
<layers>
	<id>1</id>
	<name>2010 Census ZIP Code Tabulation Areas</name>
	<parentLayerId>-1</parentLayerId>
	<defaultVisibility>true</defaultVisibility>
	<subLayerIds>null</subLayerIds>
	<minScale>3000000</minScale>
	<maxScale>1001</maxScale>
</layers>
<layers>
	<id>2</id>
	<name>ACS 2019</name>
	<parentLayerId>-1</parentLayerId>
	<defaultVisibility>true</defaultVisibility>
	<subLayerIds>3</subLayerIds>
	<subLayerIds>4</subLayerIds>
	<minScale>0</minScale>
	<maxScale>0</maxScale>
</layers>
<layers>
	<id>3</id>
	<name>2010 Census Public Use Microdata Areas</name>
	<parentLayerId>2</parentLayerId>
	<defaultVisibility>true</defaultVisibility>
	<subLayerIds>null</subLayerIds>
	<minScale>12000000</minScale>
	<maxScale>1001</maxScale>
</layers>
<layers>
	<id>4</id>
	<name>2010 Census ZIP Code Tabulation Areas</name>
	<parentLayerId>2</parentLayerId>
	<defaultVisibility>true</defaultVisibility>
	<subLayerIds>null</subLayerIds>
	<minScale>3000000</minScale>
	<maxScale>1001</maxScale>
</layers>
<layers>
	<id>5</id>
	<name>ACS 2018</name>
	<parentLayerId>-1</parentLayerId>
	<defaultVisibility>false</defaultVisibility>
	<subLayerIds>6</subLayerIds>
	<subLayerIds>7</subLayerIds>
	<minScale>0</minScale>
	<maxScale>0</maxScale>
</layers>
<layers>
	<id>6</id>
	<name>2010 Census Public Use Microdata Areas</name>
	<parentLayerId>5</parentLayerId>
	<defaultVisibility>true</defaultVisibility>
	<subLayerIds>null</subLayerIds>
	<minScale>12000000</minScale>
	<maxScale>1001</maxScale>
</layers>
<layers>
	<id>7</id>
	<name>2010 Census ZIP Code Tabulation Areas</name>
	<parentLayerId>5</parentLayerId>
	<defaultVisibility>true</defaultVisibility>
	<subLayerIds>null</subLayerIds>
	<minScale>3000000</minScale>
	<maxScale>1001</maxScale>
</layers>
<layers>
	<id>8</id>
	<name>Census 2010</name>
	<parentLayerId>-1</parentLayerId>
	<defaultVisibility>false</defaultVisibility>
	<subLayerIds>9</subLayerIds>
	<subLayerIds>10</subLayerIds>
	<subLayerIds>11</subLayerIds>
	<subLayerIds>12</subLayerIds>
	<subLayerIds>13</subLayerIds>
	<minScale>0</minScale>
	<maxScale>0</maxScale>
</layers>
<layers>
	<id>9</id>
	<name>Public Use Microdata Areas</name>
	<parentLayerId>8</parentLayerId>
	<defaultVisibility>true</defaultVisibility>
	<subLayerIds>null</subLayerIds>
	<minScale>12000000</minScale>
	<maxScale>1001</maxScale>
</layers>
<layers>
	<id>10</id>
	<name>Traffic Analysis Districts</name>
	<parentLayerId>8</parentLayerId>
	<defaultVisibility>true</defaultVisibility>
	<subLayerIds>null</subLayerIds>
	<minScale>6000000</minScale>
	<maxScale>1001</maxScale>
</layers>
<layers>
	<id>11</id>
	<name>Traffic Analysis Zones</name>
	<parentLayerId>8</parentLayerId>
	<defaultVisibility>true</defaultVisibility>
	<subLayerIds>null</subLayerIds>
	<minScale>650000</minScale>
	<maxScale>1001</maxScale>
</layers>
<layers>
	<id>12</id>
	<name>Urban Growth Areas</name>
	<parentLayerId>8</parentLayerId>
	<defaultVisibility>true</defaultVisibility>
	<subLayerIds>null</subLayerIds>
	<minScale>1400000</minScale>
	<maxScale>1001</maxScale>
</layers>
<layers>
	<id>13</id>
	<name>ZIP Code Tabulation Areas</name>
	<parentLayerId>8</parentLayerId>
	<defaultVisibility>true</defaultVisibility>
	<subLayerIds>null</subLayerIds>
	<minScale>3000000</minScale>
	<maxScale>1001</maxScale>
</layers>
<spatialReference>
	<wkid>102100</wkid>
	<latestWkid>3857</latestWkid>
</spatialReference>
<singleFusedMapCache>false</singleFusedMapCache>
<initialExtent>
	<xmin>-1.3831017391030507E7</xmin>
	<ymin>5315030.248686009</ymin>
	<xmax>-1.3162149386627829E7</xmax>
	<ymax>5790222.86573791</ymax>
	<spatialReference>
		<wkid>102100</wkid>
		<latestWkid>3857</latestWkid>
	</spatialReference>
</initialExtent>
<fullExtent>
	<xmin>-20037700</xmin>
	<ymin>-1678452.6019</ymin>
	<xmax>2.02343675425E7</xmax>
	<ymax>1.16526615375E7</ymax>
	<spatialReference>
		<wkid>102100</wkid>
		<latestWkid>3857</latestWkid>
	</spatialReference>
</fullExtent>
<minScale>12000000</minScale>
<maxScale>1001</maxScale>
<units>esriMeters</units>
<supportedImageFormatTypes>PNG32,PNG24,PNG,JPG,DIB,TIFF,EMF,PS,PDF,GIF,SVG,SVGZ,BMP</supportedImageFormatTypes>
<documentInfo>
	<Title/>
	<Author/>
	<Comments/>
	<Subject/>
	<Category/>
	<AntialiasingMode>None</AntialiasingMode>
	<TextAntialiasingMode>Force</TextAntialiasingMode>
	<Keywords/>
</documentInfo>
<capabilities>Map,Data,Query</capabilities>
<supportedQueryFormats>JSON, AMF, geoJSON</supportedQueryFormats>
<exportTilesAllowed>false</exportTilesAllowed>
<datumTransformations>
	<geoTransforms>
		<wkid>108001</wkid>
		<latestWkid>1241</latestWkid>
		<transformForward>true</transformForward>
		<name>NAD_1927_To_NAD_1983_NADCON</name>
	</geoTransforms>
</datumTransformations>
<datumTransformations>
	<geoTransforms>
		<wkid>108001</wkid>
		<latestWkid>1241</latestWkid>
		<transformForward>false</transformForward>
		<name>NAD_1927_To_NAD_1983_NADCON</name>
	</geoTransforms>
</datumTransformations>
<datumTransformations>
	<geoTransforms>
		<wkt>GEOGTRAN[&quot;WGS_1984_Major_Auxiliary_Sphere_To_WGS_1984&quot;,GEOGCS[&quot;GCS_WGS_1984_Major_Auxiliary_Sphere&quot;,DATUM[&quot;D_WGS_1984_Major_Auxiliary_Sphere&quot;,SPHEROID[&quot;WGS_1984_Major_Auxiliary_Sphere&quot;,6378137.0,0.0]],PRIMEM[&quot;Greenwich&quot;,0.0],UNIT[&quot;Degree&quot;,0.0174532925199433]],GEOGCS[&quot;GCS_WGS_1984&quot;,DATUM[&quot;D_WGS_1984&quot;,SPHEROID[&quot;WGS_1984&quot;,6378137.0,298.257223563]],PRIMEM[&quot;Greenwich&quot;,0.0],UNIT[&quot;Degree&quot;,0.0174532925199433]],METHOD[&quot;Longitude_Rotation&quot;]]</wkt>
		<transformForward>true</transformForward>
		<name>WGS_1984_Major_Auxiliary_Sphere_To_WGS_1984</name>
	</geoTransforms>
</datumTransformations>
<datumTransformations>
	<geoTransforms>
		<wkt>GEOGTRAN[&quot;WGS_1984_Major_Auxiliary_Sphere_To_WGS_1984&quot;,GEOGCS[&quot;GCS_WGS_1984_Major_Auxiliary_Sphere&quot;,DATUM[&quot;D_WGS_1984_Major_Auxiliary_Sphere&quot;,SPHEROID[&quot;WGS_1984_Major_Auxiliary_Sphere&quot;,6378137.0,0.0]],PRIMEM[&quot;Greenwich&quot;,0.0],UNIT[&quot;Degree&quot;,0.0174532925199433]],GEOGCS[&quot;GCS_WGS_1984&quot;,DATUM[&quot;D_WGS_1984&quot;,SPHEROID[&quot;WGS_1984&quot;,6378137.0,298.257223563]],PRIMEM[&quot;Greenwich&quot;,0.0],UNIT[&quot;Degree&quot;,0.0174532925199433]],METHOD[&quot;Longitude_Rotation&quot;]]</wkt>
		<transformForward>false</transformForward>
		<name>WGS_1984_Major_Auxiliary_Sphere_To_WGS_1984</name>
	</geoTransforms>
</datumTransformations>
<datumTransformations>
	<geoTransforms>
		<wkid>8088</wkid>
		<latestWkid>1188</latestWkid>
		<transformForward>true</transformForward>
		<name>NAD_1983_To_WGS_1984_1</name>
	</geoTransforms>
</datumTransformations>
<datumTransformations>
	<geoTransforms>
		<wkid>8088</wkid>
		<latestWkid>1188</latestWkid>
		<transformForward>false</transformForward>
		<name>NAD_1983_To_WGS_1984_1</name>
	</geoTransforms>
</datumTransformations>
<supportsDatumTransformation>true</supportsDatumTransformation>
<maxRecordCount>100000</maxRecordCount>
<maxImageHeight>4096</maxImageHeight>
<maxImageWidth>4096</maxImageWidth>
<supportedExtensions/>
	</REST_File>

=== mattCensus/RESTWGPM/RESTJSONXML/TIGERweb_Tracts_Blocks.xml
<?xml version="1.0" encoding="UTF-8"?>
<REST_File xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="RESTJSONXML/RESTJSONXML.xsd">
    
<currentVersion>10.51</currentVersion>
<serviceDescription/>
<mapName>Census Tracts and Blocks</mapName>
<description>Census Tracts, Census Block Groups, Census Blocks</description>
<copyrightText>Source: U.S. Census Bureau</copyrightText>
<supportsDynamicLayers>false</supportsDynamicLayers>
    <URL>https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Tracts_Blocks/MapServer</URL>
<layers>
    <id>0</id>
    <name>Census Tracts</name>
    <parentLayerId>-1</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>1400000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>1</id>
    <name>Census Block Groups</name>
    <parentLayerId>-1</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>155000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>2</id>
    <name>2010 Census Blocks</name>
    <parentLayerId>-1</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>42000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>3</id>
    <name>ACS 2019</name>
    <parentLayerId>-1</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>4</subLayerIds>
    <subLayerIds>5</subLayerIds>
    <minScale>0</minScale>
    <maxScale>0</maxScale>
</layers>
<layers>
    <id>4</id>
    <name>Census Tracts</name>
    <parentLayerId>3</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>1400000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>5</id>
    <name>Census Block Groups</name>
    <parentLayerId>3</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>155000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>6</id>
    <name>ACS 2018</name>
    <parentLayerId>-1</parentLayerId>
    <defaultVisibility>false</defaultVisibility>
    <subLayerIds>7</subLayerIds>
    <subLayerIds>8</subLayerIds>
    <minScale>0</minScale>
    <maxScale>0</maxScale>
</layers>
<layers>
    <id>7</id>
    <name>Census Tracts</name>
    <parentLayerId>6</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>1400000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>8</id>
    <name>Census Block Groups</name>
    <parentLayerId>6</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>155000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>9</id>
    <name>Census 2010</name>
    <parentLayerId>-1</parentLayerId>
    <defaultVisibility>false</defaultVisibility>
    <subLayerIds>10</subLayerIds>
    <subLayerIds>11</subLayerIds>
    <subLayerIds>12</subLayerIds>
    <minScale>0</minScale>
    <maxScale>0</maxScale>
</layers>
<layers>
    <id>10</id>
    <name>Census Tracts</name>
    <parentLayerId>9</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>1400000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>11</id>
    <name>Census Block Groups</name>
    <parentLayerId>9</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>155000</minScale>
    <maxScale>1001</maxScale>
</layers>
<layers>
    <id>12</id>
    <name>Census Blocks</name>
    <parentLayerId>9</parentLayerId>
    <defaultVisibility>true</defaultVisibility>
    <subLayerIds>null</subLayerIds>
    <minScale>42000</minScale>
    <maxScale>1001</maxScale>
</layers>
<spatialReference>
    <wkid>102100</wkid>
    <latestWkid>3857</latestWkid>
</spatialReference>
<singleFusedMapCache>false</singleFusedMapCache>
<initialExtent>
    <xmin>-9184155.18168631</xmin>
    <ymin>3941007.1761029866</ymin>
    <xmax>-9158236.546515705</xmax>
    <ymax>3959420.890013748</ymax>
    <spatialReference>
        <wkid>102100</wkid>
        <latestWkid>3857</latestWkid>
    </spatialReference>
</initialExtent>
<fullExtent>
    <xmin>-20037700</xmin>
    <ymin>-1823163.166</ymin>
    <xmax>2.01161361532E7</xmax>
    <ymax>1.16719314944E7</ymax>
    <spatialReference>
        <wkid>102100</wkid>
        <latestWkid>3857</latestWkid>
    </spatialReference>
</fullExtent>
<minScale>1400000</minScale>
<maxScale>1001</maxScale>
<units>esriMeters</units>
<supportedImageFormatTypes>PNG32,PNG24,PNG,JPG,DIB,TIFF,EMF,PS,PDF,GIF,SVG,SVGZ,BMP</supportedImageFormatTypes>
<documentInfo>
    <Title/>
    <Author/>
    <Comments/>
    <Subject/>
    <Category/>
    <AntialiasingMode>None</AntialiasingMode>
    <TextAntialiasingMode>Force</TextAntialiasingMode>
    <Keywords/>
</documentInfo>
<capabilities>Map,Data,Query</capabilities>
<supportedQueryFormats>JSON, AMF, geoJSON</supportedQueryFormats>
<exportTilesAllowed>false</exportTilesAllowed>
<datumTransformations>
    <geoTransforms>
        <wkid>108001</wkid>
        <latestWkid>1241</latestWkid>
        <transformForward>true</transformForward>
        <name>NAD_1927_To_NAD_1983_NADCON</name>
    </geoTransforms>
</datumTransformations>
<datumTransformations>
    <geoTransforms>
        <wkid>108001</wkid>
        <latestWkid>1241</latestWkid>
        <transformForward>false</transformForward>
        <name>NAD_1927_To_NAD_1983_NADCON</name>
    </geoTransforms>
</datumTransformations>
<datumTransformations>
    <geoTransforms>
        <wkt>GEOGTRAN[&quot;WGS_1984_Major_Auxiliary_Sphere_To_WGS_1984&quot;,GEOGCS[&quot;GCS_WGS_1984_Major_Auxiliary_Sphere&quot;,DATUM[&quot;D_WGS_1984_Major_Auxiliary_Sphere&quot;,SPHEROID[&quot;WGS_1984_Major_Auxiliary_Sphere&quot;,6378137.0,0.0]],PRIMEM[&quot;Greenwich&quot;,0.0],UNIT[&quot;Degree&quot;,0.0174532925199433]],GEOGCS[&quot;GCS_WGS_1984&quot;,DATUM[&quot;D_WGS_1984&quot;,SPHEROID[&quot;WGS_1984&quot;,6378137.0,298.257223563]],PRIMEM[&quot;Greenwich&quot;,0.0],UNIT[&quot;Degree&quot;,0.0174532925199433]],METHOD[&quot;Longitude_Rotation&quot;]]</wkt>
        <transformForward>true</transformForward>
        <name>WGS_1984_Major_Auxiliary_Sphere_To_WGS_1984</name>
    </geoTransforms>
</datumTransformations>
<datumTransformations>
    <geoTransforms>
        <wkt>GEOGTRAN[&quot;WGS_1984_Major_Auxiliary_Sphere_To_WGS_1984&quot;,GEOGCS[&quot;GCS_WGS_1984_Major_Auxiliary_Sphere&quot;,DATUM[&quot;D_WGS_1984_Major_Auxiliary_Sphere&quot;,SPHEROID[&quot;WGS_1984_Major_Auxiliary_Sphere&quot;,6378137.0,0.0]],PRIMEM[&quot;Greenwich&quot;,0.0],UNIT[&quot;Degree&quot;,0.0174532925199433]],GEOGCS[&quot;GCS_WGS_1984&quot;,DATUM[&quot;D_WGS_1984&quot;,SPHEROID[&quot;WGS_1984&quot;,6378137.0,298.257223563]],PRIMEM[&quot;Greenwich&quot;,0.0],UNIT[&quot;Degree&quot;,0.0174532925199433]],METHOD[&quot;Longitude_Rotation&quot;]]</wkt>
        <transformForward>false</transformForward>
        <name>WGS_1984_Major_Auxiliary_Sphere_To_WGS_1984</name>
    </geoTransforms>
</datumTransformations>
<datumTransformations>
    <geoTransforms>
        <wkid>8088</wkid>
        <latestWkid>1188</latestWkid>
        <transformForward>true</transformForward>
        <name>NAD_1983_To_WGS_1984_1</name>
    </geoTransforms>
</datumTransformations>
<datumTransformations>
    <geoTransforms>
        <wkid>8088</wkid>
        <latestWkid>1188</latestWkid>
        <transformForward>false</transformForward>
        <name>NAD_1983_To_WGS_1984_1</name>
    </geoTransforms>
</datumTransformations>
<supportsDatumTransformation>true</supportsDatumTransformation>
<maxRecordCount>100000</maxRecordCount>
<maxImageHeight>4096</maxImageHeight>
<maxImageWidth>4096</maxImageWidth>
<supportedExtensions/>
</REST_File>
